name: Build and Publish Container

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and Push to GitHub Packages
      env:
        REGISTRY: ghcr.io
        IMAGE_NAME: Golemyte/ue19_labo09-10
      run: |
        echo ${{ secrets.GITHUB_TOKEN }} | docker login $REGISTRY -u $GITHUB_ACTOR --password-stdin
        docker buildx create --use
        docker buildx build --platform linux/amd64,linux/arm64 -t $REGISTRY/$IMAGE_NAME:latest . --push
